global:
  resolve_timeout: 5m
  slack_api_url: '${SLACK_WEBHOOK_URL}'

route:
  group_by: ['alertname', 'cluster', 'service']
  group_wait: 10s
  group_interval: 10s
  repeat_interval: 1h
  receiver: 'default'
  
  routes:
    - match:
        severity: critical
      receiver: slack-critical
      continue: true
      
    - match:
        severity: warning
      receiver: slack-warning
      
    - match:
        component: outbox
      receiver: backend-oncall

receivers:
  - name: 'default'
    webhook_configs:
      - url: 'http://host.docker.internal:4001/webhook/alerts'
        send_resolved: true

  - name: 'slack-critical'
    slack_configs:
      - channel: '#alerts-critical'
        title: '🚨 Critical Alert'
        text: '{{ range .Alerts }}{{ .Annotations.summary }}{{ end }}'
        send_resolved: true
        actions:
          - type: button
            text: 'View in Grafana'
            url: 'http://localhost:3001'
          - type: button
            text: 'Runbook'
            url: '{{ .Annotations.runbook_url }}'

  - name: 'slack-warning'
    slack_configs:
      - channel: '#alerts-warning'
        title: '⚠️ Warning Alert'
        text: '{{ range .Alerts }}{{ .Annotations.summary }}{{ end }}'
        send_resolved: true

  - name: 'backend-oncall'
    email_configs:
      - to: 'backend-oncall@novagift.com'
        from: 'alerts@novagift.com'
        smarthost: 'smtp.gmail.com:587'
        auth_username: '${SMTP_USERNAME}'
        auth_password: '${SMTP_PASSWORD}'
        headers:
          Subject: 'NovaGift Alert: {{ .GroupLabels.alertname }}'

inhibit_rules:
  - source_match:
      severity: 'critical'
    target_match:
      severity: 'warning'
    equal: ['alertname', 'cluster', 'service']